### PR TITLE
v3.0.0

### LINKED ISSUE #123: Support For Apollo Server 2.0
Upgrading to apollo-server-express 2 breaks this package.

### PR DESCRIPTION
**Pull request by lorensr**
Fixes #123 

See new docs: https://github.com/apollographql/apollo-client/pull/3739

### CODE REVIEW

**Comment by moberegger** [comment]
I think it would be nice to include the convenient [meteorAccountsLink](https://github.com/apollographql/meteor-integration/blob/v2/src/main-client.js#L8) from v2 for those not using Apollo Boost. Perhaps make it a [lazy module](https://github.com/meteor/meteor/blob/devel/History.md#v1422-2016-11-15), too!

```
api.mainModule("client.js", "client", { lazy: true });
```

**Comment by lorensr** [comment]
Thanks, good point! Added a `MeteorAccountsLink()` that can take a variable header field name. Docs PR updated as well

**Comment by moberegger** [comment]
Nice! Thank you for doing this!

**Comment by TanguyCazalets** [comment]
Thank you so much for this, do you think it's going to be merge soon ?

**Pull request merged**
